Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src	= Glob('*.c')


CPPPATH = [cwd]
group = []

if GetDepend(['RT_USING_EMWINDEMO']):
    group = DefineGroup('emWin_Demo', src, depend = ['RT_USING_EMWINDEMO'], CPPPATH = CPPPATH)

Return('group')