Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src	= Glob('*.c')

# remove no need file.
if GetDepend('RT_USING_LWIP') == False:
	SrcRemove(src, 'stm32_eth.c')

if GetDepend('RT_USING_SPI') == False:
	SrcRemove(src, 'rt_stm32f10x_spi.c')
	SrcRemove(src, 'msd.c')

if GetDepend('RT_USING_RTGUI')== False:
    SrcRemove(src, 'calculator.c')
    SrcRemove(src, 'touch_spi.c')
    SrcRemove(src, 'lcd_ssd1289.c')	

if GetDepend('RT_USING_RF') == False:
	SrcRemove(src, 'NRF24L01.c')
	SrcRemove(src, 'NRF24L012.c')
	SrcRemove(src, 'rfspi.c')
	
CPPPATH = [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
