# for module compiling
import os
Import('RTT_ROOT')

cwd = str(Dir('#'))
objs = []
list = os.listdir(cwd)

objs += SConscript(cwd + "/../../Libraries/SConscript")
objs += SConscript(cwd + "/../../drivers/SConscript")
objs += SConscript(cwd + "/../../drivers/emWin_Config/SConscript")
objs += SConscript(cwd + "/../../drivers/emWin_Demo/SConscript")
objs += SConscript(cwd + "/../../Libraries/STemWinLibrary522/SConscript")

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')
