Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'applications')
src	= Glob('*.c')
CPPPATH = [cwd, str(Dir('#'))]

if GetDepend('RT_USING_RTGUI')== False:
    SrcRemove(src, 'setup.c')
    SrcRemove(src, 'ui_button.c')	
	
group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
